name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: 89536
        private_key: ${{ secrets.XUWEI_K_BOT_SECRET }}
    - uses: scala-steward-org/scala-steward-action@v2
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        author-email: "74788111+xuwei-k-bot[bot]@users.noreply.github.com"
        author-name: xuwei-k-bot[bot]
